/***********************************************************************/
/*                                                                     */
/*  FILE        :EcuHackTests.c                                        */
/*  DATE        :Fri, Jan 27, 2012                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7058F                                               */
/*                                                                     */
/*  This file is generated by KPIT GNU Project Generator.              */
/*                                                                     */
/***********************************************************************/
         
