################################################
# Make file generated by HEW
#

############################
# Toolchain directory define
# If incorrect, change to the location of the KPIT GNUSH [ELF] Toolchain toolchain
TC_INSTALL_DIR = c:\\PROGRA~1\\renesas\\hew\\tools\\KPITCU~1\\GNUSH-~1\\v11.02

###############################################################################
# The following environment variables are for building the makefile inside HEW:
# TARGET_LIB=c:\program files\renesas\hew\tools\kpit cummins\gnush-elf\v11.02\Sh-elf\sh-elf\lib
# MAKE_MODE=unix
# PATH=c:\program files\renesas\hew\tools\kpit cummins\gnush-elf\v11.02\Sh-elf\bin;c:\program files\renesas\hew\tools\kpit cummins\gnush-elf\v11.02\sh-elf\sh-elf\bin;c:\program files\renesas\hew\tools\kpit cummins\gnush-elf\v11.02\sh-elf\libexec\gcc\sh-elf\4.5-GNUSH_v11.02;C:\Windows\system32\
# TARGET_M2_LIB=c:\program files\renesas\hew\tools\kpit cummins\gnush-elf\v11.02\Sh-elf\sh-elf\lib\m2
# LIB_TARGET_INCLUDE=c:\program files\renesas\hew\tools\kpit cummins\gnush-elf\v11.02\Sh-elf\lib\gcc\sh-elf\4.5-GNUSH_v11.02\include
# TARGET_INCLUDE=c:\program files\renesas\hew\tools\kpit cummins\gnush-elf\v11.02\Sh-elf\sh-elf\include
# LIB_M2_LIB=c:\program files\renesas\hew\tools\kpit cummins\gnush-elf\v11.02\Sh-elf\lib\gcc\sh-elf\4.5-GNUSH_v11.02\m2
# INCLUDE=c:\program files\renesas\hew\tools\kpit cummins\gnush-elf\v11.02\Sh-elf\include
#

#####################################################
#
# Details:
#   Project: EcuHackTests
#   Configuration: Debug
#   Toolchain: KPIT GNUSH [ELF] Toolchain
#
#####################################################

################
# Main Defines

# GNU Library Generator01 phase

ECUHACKTESTS_DEBUG_LIBRARY_GENERATOR01_EXE=sh-elf-libgen-wrapper.exe
ECUHACKTESTS_DEBUG_LIBRARY_GENERATOR01_OUTFILESC0=..\\EcuHackTests\\Debug\\libEcuHackTests.a

# GNU Compiler02 phase

ECUHACKTESTS_DEBUG_COMPILER02_EXE=sh-elf-gcc-wrapper.exe
ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC0=..\\EcuHackTests\\Debug\\EcuHackTests.o
ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC1=..\\EcuHackTests\\Debug\\TestUtilities.o
ECUHACKTESTS_DEBUG_COMPILER02_DEPFILESC1=..\\EcuHacks2\\EcuHacks.h
ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC2=..\\EcuHackTests\\Debug\\RevLimiterTests.o
ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC3=..\\EcuHackTests\\Debug\\SpeedDensityTests.o

# GNU Assembler03 phase

ECUHACKTESTS_DEBUG_ASSEMBLER03_EXE=sh-elf-as-wrapper.exe
ECUHACKTESTS_DEBUG_ASSEMBLER03_OUTFILESC0=..\\EcuHackTests\\Debug\\ResetHandler.o

# GNU Linker04 phase

ECUHACKTESTS_DEBUG_LINKER04_EXE=sh-elf-ld-wrapper.exe
ECUHACKTESTS_DEBUG_LINKER04_INFILESC0=..\\EcuHackTests\\Debug\\EcuHackTests.o ..\\EcuHackTests\\Debug\\ResetHandler.o ..\\EcuHackTests\\Debug\\RevLimiterTests.o \
	..\\EcuHackTests\\Debug\\SpeedDensityTests.o ..\\EcuHackTests\\Debug\\TestUtilities.o
ECUHACKTESTS_DEBUG_LINKER04_OUTFILESC0=..\\EcuHackTests\\Debug\\EcuHackTests.mot ..\\EcuHackTests\\Debug\\EcuHackTests.x

#######################
# nmake "all" statement

ALL:	$(ECUHACKTESTS_DEBUG_LIBRARY_GENERATOR01_OUTFILESC0) \
	$(ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC0) \
	$(ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC1) \
	$(ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC2) \
	$(ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC3) \
	$(ECUHACKTESTS_DEBUG_ASSEMBLER03_OUTFILESC0) \
	$(ECUHACKTESTS_DEBUG_LINKER04_OUTFILESC0)

####################
# Description blocks

#
# Executing GNU Library Generator01 phase
#

$(ECUHACKTESTS_DEBUG_LIBRARY_GENERATOR01_OUTFILESC0) : 
	$(EXEDIR)\\$(ECUHACKTESTS_DEBUG_LIBRARY_GENERATOR01_EXE) -subcommand=lib0001.sub

#
# Executing GNU Compiler02 phase
#

$(ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC0) : ..\\EcuHackTests\\EcuHackTests.c
	$(EXEDIR)\\$(ECUHACKTESTS_DEBUG_COMPILER02_EXE) -subcommand=cmp0001.sub

$(ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC1) : ..\\EcuHacks2\\TestUtilities.c $(ECUHACKTESTS_DEBUG_COMPILER02_DEPFILESC1)
	$(EXEDIR)\\$(ECUHACKTESTS_DEBUG_COMPILER02_EXE) -subcommand=cmp0002.sub

$(ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC2) : ..\\EcuHacks2\\RevLimiterTests.c $(ECUHACKTESTS_DEBUG_COMPILER02_DEPFILESC1)
	$(EXEDIR)\\$(ECUHACKTESTS_DEBUG_COMPILER02_EXE) -subcommand=cmp0003.sub

$(ECUHACKTESTS_DEBUG_COMPILER02_OUTFILESC3) : ..\\EcuHacks2\\SpeedDensityTests.c $(ECUHACKTESTS_DEBUG_COMPILER02_DEPFILESC1)
	$(EXEDIR)\\$(ECUHACKTESTS_DEBUG_COMPILER02_EXE) -subcommand=cmp0004.sub

#
# Executing GNU Assembler03 phase
#

$(ECUHACKTESTS_DEBUG_ASSEMBLER03_OUTFILESC0) : ..\\EcuHacks2\\ResetHandler.s
	$(EXEDIR)\\$(ECUHACKTESTS_DEBUG_ASSEMBLER03_EXE) -subcommand=asm0001.sub

#
# Executing GNU Linker04 phase
#

$(ECUHACKTESTS_DEBUG_LINKER04_OUTFILESC0) : $(ECUHACKTESTS_DEBUG_LINKER04_INFILESC0)
	$(EXEDIR)\\$(ECUHACKTESTS_DEBUG_LINKER04_EXE) -subcommand=lnk0001.sub

