################################################
# Make file generated by HEW
#

############################
# Toolchain directory define
# If incorrect, change to the location of the KPIT GNUSH [ELF] Toolchain toolchain
TC_INSTALL_DIR = c:\program files\renesas\hew\tools\kpit cummins\gnush-elf\v11.02

#####################################################
#
# Details:
#   Project: EcuHacks2
#   Configuration: Debug
#   Toolchain: KPIT GNUSH [ELF] Toolchain
#
#####################################################

################
# Main Defines

# GNU Library Generator01 phase

ECUHACKS2_DEBUG_LIBRARY_GENERATOR01_EXE=sh-elf-libgen-wrapper.exe
ECUHACKS2_DEBUG_LIBRARY_GENERATOR01_OUTFILESC0="..\EcuHacks2\Debug\libEcuHacks2.a"

# GNU Compiler02 phase

ECUHACKS2_DEBUG_COMPILER02_EXE=sh-elf-gcc-wrapper.exe
ECUHACKS2_DEBUG_COMPILER02_OUTFILESC0="..\EcuHacks2\Debug\EcuHacks.s"
ECUHACKS2_DEBUG_COMPILER02_DEPFILESC0="..\EcuHacks2\EcuHacks.h"
ECUHACKS2_DEBUG_COMPILER02_OUTFILESC1="..\EcuHacks2\Debug\GenericTests.s"
ECUHACKS2_DEBUG_COMPILER02_OUTFILESC2="..\EcuHacks2\Debug\RevLimiter.s"
ECUHACKS2_DEBUG_COMPILER02_OUTFILESC3="..\EcuHacks2\Debug\RevLimiterTests.s"
ECUHACKS2_DEBUG_COMPILER02_OUTFILESC4="..\EcuHacks2\Debug\SpeedDensity.s"
ECUHACKS2_DEBUG_COMPILER02_OUTFILESC5="..\EcuHacks2\Debug\SpeedDensityTests.s"
ECUHACKS2_DEBUG_COMPILER02_OUTFILESC6="..\EcuHacks2\Debug\TestUtilities.s"

# GNU Assembler03 phase

ECUHACKS2_DEBUG_ASSEMBLER03_EXE=sh-elf-as-wrapper.exe
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC0="..\EcuHacks2\Debug\EndMarkers.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC1="..\EcuHacks2\Debug\Metadata.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC2="..\EcuHacks2\Debug\ResetHandler.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC3="..\EcuHacks2\Debug\RevLimiterTables.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC4="..\EcuHacks2\Debug\RomAddresses.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC5="..\EcuHacks2\Debug\SpeedDensityTables.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC6="..\EcuHacks2\Debug\EcuHacks.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC7="..\EcuHacks2\Debug\GenericTests.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC8="..\EcuHacks2\Debug\RevLimiter.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC9="..\EcuHacks2\Debug\RevLimiterTests.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC10="..\EcuHacks2\Debug\SpeedDensity.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC11="..\EcuHacks2\Debug\SpeedDensityTests.o"
ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC12="..\EcuHacks2\Debug\TestUtilities.o"

# GNU Linker04 phase

ECUHACKS2_DEBUG_LINKER04_EXE=sh-elf-ld-wrapper.exe
ECUHACKS2_DEBUG_LINKER04_INFILESC0="..\EcuHacks2\Debug\EcuHacks.o" "..\EcuHacks2\Debug\EndMarkers.o" "..\EcuHacks2\Debug\GenericTests.o" \
	"..\EcuHacks2\Debug\Metadata.o" "..\EcuHacks2\Debug\ResetHandler.o" "..\EcuHacks2\Debug\RevLimiter.o" \
	"..\EcuHacks2\Debug\RevLimiterTables.o" "..\EcuHacks2\Debug\RevLimiterTests.o" "..\EcuHacks2\Debug\RomAddresses.o" \
	"..\EcuHacks2\Debug\SpeedDensity.o" "..\EcuHacks2\Debug\SpeedDensityTables.o" "..\EcuHacks2\Debug\SpeedDensityTests.o" \
	"..\EcuHacks2\Debug\TestUtilities.o"
ECUHACKS2_DEBUG_LINKER04_OUTFILESC0="..\EcuHacks2\Debug\EcuHacks2.mot" "..\EcuHacks2\Debug\EcuHacks2.x"

#######################
# nmake "all" statement

ALL:	ECUHACKS2_DEBUG_LIBRARY_GENERATOR01_ENVC0 \
	$(ECUHACKS2_DEBUG_LIBRARY_GENERATOR01_OUTFILESC0) \
	$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC0) \
	$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC1) \
	$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC2) \
	$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC3) \
	$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC4) \
	$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC5) \
	$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC6) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC0) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC1) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC2) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC3) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC4) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC5) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC6) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC7) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC8) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC9) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC10) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC11) \
	$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC12) \
	$(ECUHACKS2_DEBUG_LINKER04_OUTFILESC0)

####################
# Description blocks

!MESSAGE
!MESSAGE Executing GNU Library Generator01 phase
!MESSAGE

ECUHACKS2_DEBUG_LIBRARY_GENERATOR01_ENVC0 : 
	set TARGET_LIB=$(TC_INSTALL_DIR)\Sh-elf\sh-elf\lib
	set MAKE_MODE=unix
	set PATH=$(TC_INSTALL_DIR)\Sh-elf\bin;$(TC_INSTALL_DIR)\sh-elf\sh-elf\bin;$(TC_INSTALL_DIR)\sh-elf\libexec\gcc\sh-elf\4.5-GNUSH_v11.02;C:\Windows\system32\
	set TARGET_M2_LIB=$(TC_INSTALL_DIR)\Sh-elf\sh-elf\lib\m2
	set LIB_TARGET_INCLUDE=$(TC_INSTALL_DIR)\Sh-elf\lib\gcc\sh-elf\4.5-GNUSH_v11.02\include
	set TARGET_INCLUDE=$(TC_INSTALL_DIR)\Sh-elf\sh-elf\include
	set LIB_M2_LIB=$(TC_INSTALL_DIR)\Sh-elf\lib\gcc\sh-elf\4.5-GNUSH_v11.02\m2
	set INCLUDE=$(TC_INSTALL_DIR)\Sh-elf\include

$(ECUHACKS2_DEBUG_LIBRARY_GENERATOR01_OUTFILESC0) : 
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_LIBRARY_GENERATOR01_EXE)" -subcommand=<<
--compiler-options=-m2e,-Os,-fdata-sections,-ffunction-sections,-falign-jumps,-fno-function-cse,-funit-at-a-time
--output="..\EcuHacks2\Debug\libEcuHacks2.a"
--select-lib=optlib
--header-files=ctype
<<

!MESSAGE
!MESSAGE Executing GNU Compiler02 phase
!MESSAGE

$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC0) : "..\EcuHacks2\EcuHacks.c" $(ECUHACKS2_DEBUG_COMPILER02_DEPFILESC0)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_COMPILER02_EXE)" -subcommand=<<
-m2e
-I "$$(TC_INSTALL_DIR)\sh-elf\sh-elf\optlibinc"
-I "$$(TC_INSTALL_DIR)\sh-elf\lib\gcc\sh-elf\4.5-GNUSH_v11.02\optlibinc"
-D DEBUG
-g
-g2
-S -o "..\EcuHacks2\Debug\EcuHacks.s"
-nostdinc
"..\EcuHacks2\EcuHacks.c"
-Wa,-gdwarf2
<<

$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC1) : "..\EcuHacks2\GenericTests.c" $(ECUHACKS2_DEBUG_COMPILER02_DEPFILESC0)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_COMPILER02_EXE)" -subcommand=<<
-m2e
-I "$$(TC_INSTALL_DIR)\sh-elf\sh-elf\optlibinc"
-I "$$(TC_INSTALL_DIR)\sh-elf\lib\gcc\sh-elf\4.5-GNUSH_v11.02\optlibinc"
-D DEBUG
-g
-g2
-S -o "..\EcuHacks2\Debug\GenericTests.s"
-nostdinc
"..\EcuHacks2\GenericTests.c"
-Wa,-gdwarf2
<<

$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC2) : "..\EcuHacks2\RevLimiter.c" $(ECUHACKS2_DEBUG_COMPILER02_DEPFILESC0)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_COMPILER02_EXE)" -subcommand=<<
-m2e
-I "$$(TC_INSTALL_DIR)\sh-elf\sh-elf\optlibinc"
-I "$$(TC_INSTALL_DIR)\sh-elf\lib\gcc\sh-elf\4.5-GNUSH_v11.02\optlibinc"
-D DEBUG
-g
-g2
-S -o "..\EcuHacks2\Debug\RevLimiter.s"
-nostdinc
"..\EcuHacks2\RevLimiter.c"
-Wa,-gdwarf2
<<

$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC3) : "..\EcuHacks2\RevLimiterTests.c" $(ECUHACKS2_DEBUG_COMPILER02_DEPFILESC0)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_COMPILER02_EXE)" -subcommand=<<
-m2e
-I "$$(TC_INSTALL_DIR)\sh-elf\sh-elf\optlibinc"
-I "$$(TC_INSTALL_DIR)\sh-elf\lib\gcc\sh-elf\4.5-GNUSH_v11.02\optlibinc"
-D DEBUG
-g
-g2
-S -o "..\EcuHacks2\Debug\RevLimiterTests.s"
-nostdinc
"..\EcuHacks2\RevLimiterTests.c"
-Wa,-gdwarf2
<<

$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC4) : "..\EcuHacks2\SpeedDensity.c" $(ECUHACKS2_DEBUG_COMPILER02_DEPFILESC0)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_COMPILER02_EXE)" -subcommand=<<
-m2e
-I "$$(TC_INSTALL_DIR)\sh-elf\sh-elf\optlibinc"
-I "$$(TC_INSTALL_DIR)\sh-elf\lib\gcc\sh-elf\4.5-GNUSH_v11.02\optlibinc"
-D DEBUG
-g
-g2
-S -o "..\EcuHacks2\Debug\SpeedDensity.s"
-nostdinc
"..\EcuHacks2\SpeedDensity.c"
-Wa,-gdwarf2
<<

$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC5) : "..\EcuHacks2\SpeedDensityTests.c" $(ECUHACKS2_DEBUG_COMPILER02_DEPFILESC0)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_COMPILER02_EXE)" -subcommand=<<
-m2e
-I "$$(TC_INSTALL_DIR)\sh-elf\sh-elf\optlibinc"
-I "$$(TC_INSTALL_DIR)\sh-elf\lib\gcc\sh-elf\4.5-GNUSH_v11.02\optlibinc"
-D DEBUG
-g
-g2
-S -o "..\EcuHacks2\Debug\SpeedDensityTests.s"
-nostdinc
"..\EcuHacks2\SpeedDensityTests.c"
-Wa,-gdwarf2
<<

$(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC6) : "..\EcuHacks2\TestUtilities.c" $(ECUHACKS2_DEBUG_COMPILER02_DEPFILESC0)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_COMPILER02_EXE)" -subcommand=<<
-m2e
-I "$$(TC_INSTALL_DIR)\sh-elf\sh-elf\optlibinc"
-I "$$(TC_INSTALL_DIR)\sh-elf\lib\gcc\sh-elf\4.5-GNUSH_v11.02\optlibinc"
-D DEBUG
-g
-g2
-S -o "..\EcuHacks2\Debug\TestUtilities.s"
-nostdinc
"..\EcuHacks2\TestUtilities.c"
-Wa,-gdwarf2
<<

!MESSAGE
!MESSAGE Executing GNU Assembler03 phase
!MESSAGE

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC0) : "..\EcuHacks2\EndMarkers.s"
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\EndMarkers.s"
-include="..\EcuHacks2"
-nodebug
-object="..\EcuHacks2\Debug\EndMarkers.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC1) : "..\EcuHacks2\Metadata.s"
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\Metadata.s"
-include="..\EcuHacks2"
-nodebug
-object="..\EcuHacks2\Debug\Metadata.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC2) : "..\EcuHacks2\ResetHandler.s"
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\ResetHandler.s"
-include="..\EcuHacks2"
-nodebug
-object="..\EcuHacks2\Debug\ResetHandler.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC3) : "..\EcuHacks2\RevLimiterTables.s"
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\RevLimiterTables.s"
-include="..\EcuHacks2"
-nodebug
-object="..\EcuHacks2\Debug\RevLimiterTables.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC4) : "..\EcuHacks2\RomAddresses.s"
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\RomAddresses.s"
-include="..\EcuHacks2"
-nodebug
-object="..\EcuHacks2\Debug\RomAddresses.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC5) : "..\EcuHacks2\SpeedDensityTables.s"
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\SpeedDensityTables.s"
-include="..\EcuHacks2"
-nodebug
-object="..\EcuHacks2\Debug\SpeedDensityTables.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC6) : $(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC0)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\Debug\EcuHacks.s"
-nodebug
-object="..\EcuHacks2\Debug\EcuHacks.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC7) : $(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC1)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\Debug\GenericTests.s"
-nodebug
-object="..\EcuHacks2\Debug\GenericTests.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC8) : $(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC2)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\Debug\RevLimiter.s"
-nodebug
-object="..\EcuHacks2\Debug\RevLimiter.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC9) : $(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC3)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\Debug\RevLimiterTests.s"
-nodebug
-object="..\EcuHacks2\Debug\RevLimiterTests.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC10) : $(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC4)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\Debug\SpeedDensity.s"
-nodebug
-object="..\EcuHacks2\Debug\SpeedDensity.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC11) : $(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC5)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\Debug\SpeedDensityTests.s"
-nodebug
-object="..\EcuHacks2\Debug\SpeedDensityTests.o"
-nolist
-nologo
<<

$(ECUHACKS2_DEBUG_ASSEMBLER03_OUTFILESC12) : $(ECUHACKS2_DEBUG_COMPILER02_OUTFILESC6)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_ASSEMBLER03_EXE)" -subcommand=<<
"..\EcuHacks2\Debug\TestUtilities.s"
-nodebug
-object="..\EcuHacks2\Debug\TestUtilities.o"
-nolist
-nologo
<<

!MESSAGE
!MESSAGE Executing GNU Linker04 phase
!MESSAGE

$(ECUHACKS2_DEBUG_LINKER04_OUTFILESC0) : $(ECUHACKS2_DEBUG_LINKER04_INFILESC0)
	"$(EXEDIR)\$(ECUHACKS2_DEBUG_LINKER04_EXE)" -subcommand=<<
noprelink
list "..\EcuHacks2\Debug\EcuHacks2.map"
nologo
"..\EcuHacks2\Debug\EcuHacks.o"
"..\EcuHacks2\Debug\EndMarkers.o"
"..\EcuHacks2\Debug\GenericTests.o"
"..\EcuHacks2\Debug\Metadata.o"
"..\EcuHacks2\Debug\ResetHandler.o"
"..\EcuHacks2\Debug\RevLimiter.o"
"..\EcuHacks2\Debug\RevLimiterTables.o"
"..\EcuHacks2\Debug\RevLimiterTests.o"
"..\EcuHacks2\Debug\RomAddresses.o"
"..\EcuHacks2\Debug\SpeedDensity.o"
"..\EcuHacks2\Debug\SpeedDensityTables.o"
"..\EcuHacks2\Debug\SpeedDensityTests.o"
"..\EcuHacks2\Debug\TestUtilities.o"
-l "libgcc.a"
-l "libgcc-Os-4-200.a"
-l "libEcuHacks2.a"
-o "..\EcuHacks2\Debug\EcuHacks2.x"
-e _ResetHandler
end
"..\EcuHacks2\Debug\EcuHacks2.x"
output "..\EcuHacks2\Debug\EcuHacks2.x"
<<

