#include "EcuHacks.h"

extern float RedlineCut, RedlineResume;
extern float LaunchControlCut, LaunchControlResume;
extern float FlatFootShiftCut, FlatFootShiftResume;
extern float FlatFootShiftSpeedThreshold;

//#define Testing

// To test, load a patched ROM and set PC to 125B0.
// You should JSR to an unrelated routine, then step through this hook, then
// step through RevLimitCode, then back out to a JSR into other ECU code.

void RevLimitPatch(void) __attribute__ ((section ("RevLimitPatch")));
void RevLimitPatch(void)
{
	// These nops align the patch code to 0x318DC.
	asm("nop");
	asm("nop");
	asm("nop");
#ifdef Testing	
	// This instruction must land at 0x318DC.
	RevLimitCode();
	asm("bra ._revLimitExit");	
#else
	// Invoke the LC/FFS rev limiter code.	
	// This is equivalent to just calling "RevLimitCode();" except that it
	// doesn't reference any memory outside of the body of this method.  That
	// should make it easy to overwrite the existing code with this patch.
	asm("nop");
	// This instruction must land at 0x318DC.
	asm("MOV.L    R14,@-R15");
	asm("sts.l    pr, @-r15");
	
	asm("mov.l    @(0x14,PC),r1");
	asm("jsr @r1");	
	asm("nop");
	
	asm("lds.l    @r15+, pr");
	asm("MOV.L     @R15+,R14");
	asm("bra revLimitExit");	
	asm("nop");
	asm("nop");	
	asm("nop");
	asm("nop");	
	
	// This is the address of the RevLimiterCode function, below.
	// See the ".RomHole" segment, defined in the Linker settings.
	asm(".long _RevLimiterCode");
#endif	
	// These nops do not need to be copied into the ECU image, they are just
	// here to get the _revLimitExit label to land at the correct address to
	// resume execution of the stock ECU code.
	asm("nop");
	asm("nop");	
	asm("nop");
	asm("nop");	
	asm("nop");	
	asm("nop");
	asm("nop");
	asm("nop");	
	asm("nop");
	asm("nop");	
	asm("nop");
	asm("nop");
	asm("nop");
	// This instruction must land at 0x31912
	asm("revLimitExit:");
}

void RevLimiterCode(void) __attribute__ ((section ("RomHole_RevLimiterCode")));
void RevLimiterCode()
{
	// These nopcodes are just here to make it easier to distinguish between code
	// generated by the compiler, and code I actually wrote.
	asm("nop");
	asm("nop");
	
	// These temporary variables will reside on the stack, where they will be
	// accessed via registers r14 and r15.
	float fuelCut;
	float fuelResume;
	
	// Check the clutch switch
	if (((*pCruiseFlagsA & 0x80) == 0) ||
		(pRamVariables->RevMatchState == RevMatchCalibration))
	{
		// Normal rev limiter thresholds.
		fuelCut = RedlineCut;
		fuelResume = RedlineResume;
	}
	else
	{
		if (*pSpeed > FlatFootShiftSpeedThreshold)
		{
			if (*pThrottlePedal > 90.0f)
			{
				// Flat foot shift rev limiter thresholds.
				float revMatchFuelCut = pRamVariables->UpshiftRpm + RevMatchFfsFuelCutDelta;
				float revMatchFuelResume = pRamVariables->UpshiftRpm + RevMatchFfsFuelResumeDelta;
				
				// Use the lower limit, in case of misconfiguration.
				fuelCut = revMatchFuelCut < RedlineCut ? revMatchFuelCut : RedlineCut;
				fuelResume = revMatchFuelResume < RedlineResume ? revMatchFuelResume : RedlineResume;
				
				if (fuelResume >= fuelCut)
				{
					fuelResume = fuelCut - 100;
				}
			}
			else
			{
				// Normal rev limiter thresholds.
				//
				// This code path is used when shifting gears, with
				// or without the rev match hack.
				fuelCut = RedlineCut;
				fuelResume = RedlineResume;
			}
		}
		else
		{
			// Launch control rev limiter thresholds.
			fuelCut = LaunchControlCut;
			fuelResume = LaunchControlResume;
		}
	}
	
	if (*pRPM > fuelCut)
	{
		// Set the rev-limit fuel cut flag.
		*((char*)pFlagsRevLimit_0x80) |= 0x80;
	} 
	else if (*pRPM < fuelResume)
	{
		// Clear the rev-limit fuel cut flag.
		*((char*)pFlagsRevLimit_0x80) &= 0x7F;
	}

	// More nopcodes to distingish between my code and the compiler's code.
	asm("nop");
	asm("nop");
}

void GetRevLimiterTableInfo() __attribute__ ((section ("Misc")));
void GetRevLimiterTableInfo()
{
	void* address = 0;
	
	address = &RedlineCut;
	address = &RedlineResume;
	
	address = &LaunchControlCut;
	address = &LaunchControlResume;
	
	address = &RevMatchFfsFuelCutDelta;
	address = &RevMatchFfsFuelResumeDelta;
	
	address = &FlatFootShiftSpeedThreshold;
}
